services:
  postgres:
    image: ghcr.io/jackjakarta/postgres:17
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: local-nextjs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: h4yuasd6
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d local-nextjs']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
